name: NoThanks
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle
      - name: Setup ssh keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GITHUBBOT_PRIVATE_KEY }} 
          known_hosts: unnecessary

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with gradle
        run: ./gradlew build --no-daemon
      - name: Transfer application archive to deployment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./build/libs/no-thanks.jar
          remote_path: /opt/apps/
          remote_host: ${{ secrets.GITHUBBOT_SSH_HOST }}
          remote_user: ${{ secrets.GITHUBBOT_USER }}
          remote_key: ${{ secrets.GITHUBBOT_PRIVATE_KEY }}
      - name: Deploy new version
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GITHUBBOT_SSH_HOST }}
          username: ${{ secrets.GITHUBBOT_USER }}
          key: ${{ secrets.GITHUBBOT_PRIVATE_KEY }}
          script: |
            sudo systemctl restart no-thanks